import type { Metadata } from "next";
import { DM_Sans,Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const dmsans=DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-dmsans",
})

const playfairdisplay=Playfair_Display({
  subsets: ["latin"],
  weight: [ "400", "500", "600", "700", "800", "900"],
  variable: "--font-playfairdisplay",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${playfairdisplay.variable} ${playfairdisplay.className} ${dmsans.variable} ${dmsans.className}`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
